import Foundation
import GRPCCore
import Pulse
import SwiftProtobuf
import Synchronization

/// Collects everything about one RPC attempt and logs it to Pulse exactly once.
final class RPCRecorder: Sendable {
    enum Outcome: Sendable {
        /// The response stream ended. This is only a success if trailers arrived:
        /// grpc-swift-2 also ends the stream quietly when the calling task is cancelled.
        case endOfStream
        /// The RPC ended with an error. The error's metadata are the trailers.
        case failed(RPCError, isCancelled: Bool)
        /// `next` threw before a response existed.
        case threw(any Error, isCancelled: Bool)
    }

    private struct State: Sendable {
        var requestMessages: JSONMessages
        var responseMessages: JSONMessages
        var initialMetadata: Metadata = [:]
        var trailingMetadata: Metadata?
        var isRequestFinished = false
        /// When the request producer returned.
        var requestEndDate: Date?
        /// When `next` returned, i.e. the first response part (headers or trailers-only) arrived.
        var responseStartDate: Date?
        /// An outcome waiting for the request side to finish, see `finishAfterRequest(_:)`.
        var pendingCompletion: Completion?
        var isFinished = false
    }

    /// What gets logged, fixed when the outcome is known.
    private struct Completion: Sendable {
        enum Result: Sendable {
            /// A gRPC status; `nil` means OK.
            case rpc(RPCError?, withResponse: Bool)
            /// A non-gRPC error thrown by `next`, logged unchanged.
            case other(any Error)
        }

        var result: Result
        var endDate: Date
    }

    let taskId = UUID()
    private let startDate = Date()
    private let startInstant = ContinuousClock.now
    private let timeout: Duration?
    private let request: URLRequest
    private let remotePeer: String
    private let localPeer: String
    private let logger: NetworkLogger
    private let label: String?
    private let jsonEncodingOptions: JSONEncodingOptions
    /// Whether the method has exactly one response message. `false` if the type is
    /// unknown, which it is for descriptors not generated by grpc-swift-2 2.3 or later.
    private let expectsSingleResponse: Bool
    private let state: Mutex<State>

    init(
        request: URLRequest,
        requestMetadata: Metadata,
        descriptor: MethodDescriptor,
        remotePeer: String,
        localPeer: String,
        logger: NetworkLogger,
        label: String?,
        jsonEncodingOptions: JSONEncodingOptions,
        bodySizeLimit: Int
    ) {
        self.state = Mutex(State(
            requestMessages: JSONMessages(sizeLimit: bodySizeLimit),
            responseMessages: JSONMessages(sizeLimit: bodySizeLimit)
        ))
        self.request = request
        self.expectsSingleResponse = descriptor.type.map { !$0.isResponseStreaming } ?? false
        self.remotePeer = remotePeer
        self.localPeer = localPeer
        self.timeout = Array(requestMetadata[stringValues: "grpc-timeout"]).first.flatMap(Duration.init(grpcTimeout:))
        self.logger = logger
        self.label = label
        self.jsonEncodingOptions = jsonEncodingOptions
    }

    deinit {
        // Safety net: the app stopped reading the response before it ended, or a
        // pending outcome never saw the request side finish.
        if let state = takeUnfinishedState() {
            log(state, state.pendingCompletion ?? Completion(
                result: .rpc(RPCError(code: .cancelled, message: "Response stream not fully consumed."), withResponse: true),
                endDate: Date()
            ))
        }
    }

    // MARK: Recording

    func start() {
        logger.logTaskCreated(taskId: taskId, request: request, label: label)
    }

    func recordRequestMessage(_ message: some Sendable) {
        let json = String(json: message, options: jsonEncodingOptions)
        state.withLock { state in
            if !state.isFinished { state.requestMessages.append(json) }
        }
    }

    func recordResponseMessage(_ message: some Sendable) {
        let json = String(json: message, options: jsonEncodingOptions)
        let count = state.withLock { state in
            if !state.isFinished { state.responseMessages.append(json) }
            return state.responseMessages.count
        }
        // grpc-swift-2 fails a single-response call at its second message and stops reading.
        if expectsSingleResponse && count == 2 {
            let error = RPCError(code: .unimplemented, message: "Multiple messages received, but only one is expected.")
            finish(.failed(error, isCancelled: false))
        }
    }

    func recordInitialMetadata(_ metadata: Metadata) {
        state.withLock { $0.initialMetadata = metadata }
    }

    /// Called when `next` returns a response, accepted or rejected.
    func responseDidStart() {
        let date = Date()
        state.withLock { $0.responseStartDate = $0.responseStartDate ?? date }
    }

    func recordTrailingMetadata(_ metadata: Metadata) {
        state.withLock { $0.trailingMetadata = metadata }
    }

    /// Logs the completed task. Only the first call to `finish(_:)` or
    /// `finishAfterRequest(_:)` has an effect.
    func finish(_ outcome: Outcome) {
        complete(outcome, waitsForRequest: false)
    }

    /// Like `finish(_:)`, but logs only once the request side is done.
    ///
    /// A server that rejects a call before reading it replies trailers-only, often
    /// before the request message has been written. The outcome and end date are
    /// fixed now; waiting only keeps the request body.
    func finishAfterRequest(_ outcome: Outcome) {
        complete(outcome, waitsForRequest: true)
    }

    /// Called when the request producer returns or throws.
    func requestDidFinish() {
        let date = Date()
        let finished: (State, Completion)? = state.withLock { state in
            state.isRequestFinished = true
            state.requestEndDate = date
            guard !state.isFinished, let completion = state.pendingCompletion else { return nil }
            state.isFinished = true
            return (state, completion)
        }
        if let finished {
            log(finished.0, finished.1)
        }
    }

    // MARK: Private

    private func complete(_ outcome: Outcome, waitsForRequest: Bool) {
        let endDate = Date()
        let finished: (State, Completion)? = state.withLock { state in
            guard !state.isFinished, state.pendingCompletion == nil else { return nil }
            let completion = Completion(result: result(for: outcome, state: state), endDate: endDate)
            guard !waitsForRequest || state.isRequestFinished else {
                state.pendingCompletion = completion
                return nil
            }
            state.isFinished = true
            return (state, completion)
        }
        if let finished {
            log(finished.0, finished.1)
        }
    }

    private func result(for outcome: Outcome, state: State) -> Completion.Result {
        switch outcome {
        case .endOfStream:
            // Trailers mean the server completed the call, even if the task was cancelled after.
            guard state.trailingMetadata != nil else {
                return .rpc(cancellationError(), withResponse: true)
            }
            // grpc-swift-2 fails a single-response call that ends without a message.
            if expectsSingleResponse && state.responseMessages.count == 0 {
                return .rpc(RPCError(code: .unimplemented, message: "No messages received, exactly one was expected."), withResponse: true)
            }
            return .rpc(nil, withResponse: true)
        case .failed(let error, let isCancelled):
            // Only a cancellation is replaced, so it can read as a deadline. A status from the
            // server is what the app sees, and is kept.
            return .rpc(isCancelled && error.isCancellation ? cancellationError() : error, withResponse: true)
        case .threw(let error, let isCancelled):
            if isCancelled {
                return .rpc(cancellationError(), withResponse: false)
            }
            if error is RPCError || error is any RPCErrorConvertible {
                return .rpc(RPCError(mapping: error), withResponse: false)
            }
            return .other(error)
        }
    }

    private func takeUnfinishedState() -> State? {
        state.withLock { state in
            guard !state.isFinished else { return nil }
            state.isFinished = true
            return state
        }
    }

    /// `DEADLINE_EXCEEDED` if the request's `grpc-timeout` has run out, `CANCELLED` otherwise.
    ///
    /// grpc-swift-2 computes `grpc-timeout` before it waits for a connection, while this clock
    /// starts once the stream exists. The 20 ms tolerance absorbs the usual gap; on a slow
    /// first connection a deadline can still read as `CANCELLED`, so the message says how
    /// much time was allowed and how much had passed.
    private func cancellationError() -> RPCError {
        guard let timeout else {
            return RPCError(code: .cancelled, message: "The RPC was cancelled.")
        }
        let elapsed = ContinuousClock.now - startInstant
        let details = "grpc-timeout \(timeout.formatted(.statusMessage)), \(elapsed.formatted(.statusMessage)) elapsed"
        if elapsed + .milliseconds(20) >= timeout {
            return RPCError(code: .deadlineExceeded, message: "RPC timed out before completing (\(details)).")
        }
        return RPCError(code: .cancelled, message: "The RPC was cancelled (\(details)).")
    }

    private func log(_ state: State, _ completion: Completion) {
        switch completion.result {
        case .rpc(let rpcError, let withResponse):
            let response = withResponse ? request.url.flatMap { url in
                HTTPURLResponse(
                    url: url,
                    initialMetadata: state.initialMetadata,
                    trailingMetadata: state.trailingMetadata,
                    rpcError: rpcError
                )
            } : nil
            log(state, response: response, error: rpcError.map(NSError.init), endDate: completion.endDate)
        case .other(let error):
            log(state, response: nil, error: error, endDate: completion.endDate)
        }
    }

    private func log(_ state: State, response: HTTPURLResponse?, error: (any Error)?, endDate: Date) {
        let endDate = max(endDate, startDate)
        logger.logTaskCompleted(
            taskId: taskId,
            request: request,
            response: response,
            error: error,
            requestBody: state.requestMessages.data,
            responseBody: state.responseMessages.data,
            metrics: NetworkLogger.Metrics(
                taskInterval: DateInterval(start: startDate, end: endDate),
                redirectCount: 0,
                transactions: [makeTransaction(state, response: response, endDate: endDate)]
            ),
            label: label
        )
    }

    /// One synthetic `.networkLoad` transaction, so PulseUI shows the transfer sizes and
    /// a timing chart. Body sizes are JSON sizes, including dropped messages; header sizes
    /// are uncompressed estimates.
    private func makeTransaction(_ state: State, response: HTTPURLResponse?, endDate: Date) -> NetworkLogger.TransactionMetrics {
        var transaction = NetworkLogger.TransactionMetrics(
            request: NetworkLogger.Request(request),
            response: response.map(NetworkLogger.Response.init),
            resourceFetchType: .networkLoad
        )

        let responseStartDate = response == nil ? nil : min(state.responseStartDate ?? endDate, endDate)
        transaction.timing.fetchStartDate = startDate
        transaction.timing.requestStartDate = startDate
        // Streaming calls can keep sending after the response started. The chart assumes
        // request → waiting → response, so the request end is only shown when it came first.
        if let requestEndDate = state.requestEndDate, requestEndDate <= (responseStartDate ?? endDate) {
            transaction.timing.requestEndDate = requestEndDate
        }
        transaction.timing.responseStartDate = responseStartDate
        transaction.timing.responseEndDate = endDate

        let requestBodySize = Int64(state.requestMessages.size)
        let responseBodySize = Int64(state.responseMessages.size)
        transaction.transferSize.requestHeaderBytesSent = estimatedSize(ofHeaders: request.allHTTPHeaderFields)
        transaction.transferSize.requestBodyBytesBeforeEncoding = requestBodySize
        transaction.transferSize.requestBodyBytesSent = requestBodySize
        transaction.transferSize.responseHeaderBytesReceived = estimatedSize(ofHeaders: transaction.response?.headers)
        transaction.transferSize.responseBodyBytesReceived = responseBodySize
        transaction.transferSize.responseBodyBytesAfterDecoding = responseBodySize

        // Best effort: the peer descriptions have no stable format (see `PeerAddress`). An IP
        // peer fills in the address and port like a URLSession task; any other description is
        // shown as it is, without a port.
        let remoteAddress = PeerAddress(peer: remotePeer)
        let localAddress = PeerAddress(peer: localPeer)
        transaction.remoteAddress = remoteAddress?.host ?? (remotePeer.isEmpty ? nil : remotePeer)
        transaction.remotePort = remoteAddress?.port
        transaction.localAddress = localAddress?.host ?? (localPeer.isEmpty ? nil : localPeer)
        transaction.localPort = localAddress?.port
        if remoteAddress != nil {
            // Inferred, not reported: IP peers come from the NIO transports, which speak HTTP/2.
            transaction.networkProtocol = "h2"
        }
        return transaction
    }

    /// The uncompressed size of `name: value` lines, a stand-in for header bytes on the wire
    /// (HTTP/2 compresses them with HPACK).
    private func estimatedSize(ofHeaders headers: [String: String]?) -> Int64 {
        Int64((headers ?? [:]).reduce(0) { $0 + $1.key.utf8.count + 2 + $1.value.utf8.count + 2 })
    }
}
